// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-CNHDqheCrlc6_iE5EYsXuYe5z48HfRw',
    appId: '1:430190917898:web:89ea2b40e081d3385da2f3',
    messagingSenderId: '430190917898',
    projectId: 'flutter-ordering-app-mai-dc6c8',
    authDomain: 'flutter-ordering-app-mai-dc6c8.firebaseapp.com',
    storageBucket: 'flutter-ordering-app-mai-dc6c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA0_IT2T0qFuiQjPMu-tbFujekNPXd-fE',
    appId: '1:430190917898:android:09350a69cc1282a75da2f3',
    messagingSenderId: '430190917898',
    projectId: 'flutter-ordering-app-mai-dc6c8',
    storageBucket: 'flutter-ordering-app-mai-dc6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_xd5cz9wCX30_sk2NBdFVPLdD6RStZIA',
    appId: '1:430190917898:ios:f713c4c70589023e5da2f3',
    messagingSenderId: '430190917898',
    projectId: 'flutter-ordering-app-mai-dc6c8',
    storageBucket: 'flutter-ordering-app-mai-dc6c8.appspot.com',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_xd5cz9wCX30_sk2NBdFVPLdD6RStZIA',
    appId: '1:430190917898:ios:f713c4c70589023e5da2f3',
    messagingSenderId: '430190917898',
    projectId: 'flutter-ordering-app-mai-dc6c8',
    storageBucket: 'flutter-ordering-app-mai-dc6c8.appspot.com',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-CNHDqheCrlc6_iE5EYsXuYe5z48HfRw',
    appId: '1:430190917898:web:8675f5c1d15013075da2f3',
    messagingSenderId: '430190917898',
    projectId: 'flutter-ordering-app-mai-dc6c8',
    authDomain: 'flutter-ordering-app-mai-dc6c8.firebaseapp.com',
    storageBucket: 'flutter-ordering-app-mai-dc6c8.appspot.com',
  );
}
