// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHHqMA25p-KmebPx9-NMHmuemHjjdSHZI',
    appId: '1:639240148483:web:a3bc1d8dff0521507d2036',
    messagingSenderId: '639240148483',
    projectId: 'ammarqiuckserve',
    authDomain: 'ammarqiuckserve.firebaseapp.com',
    storageBucket: 'ammarqiuckserve.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByZ_Jzlmf1AQ5C2ZY80QwlR_ru2OShkG0',
    appId: '1:639240148483:android:bb6c0086a921b71c7d2036',
    messagingSenderId: '639240148483',
    projectId: 'ammarqiuckserve',
    storageBucket: 'ammarqiuckserve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPvTa1gZ_mLIOfsz1LlETCn2R4qoSPmzk',
    appId: '1:639240148483:ios:585337a6fc40163c7d2036',
    messagingSenderId: '639240148483',
    projectId: 'ammarqiuckserve',
    storageBucket: 'ammarqiuckserve.appspot.com',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPvTa1gZ_mLIOfsz1LlETCn2R4qoSPmzk',
    appId: '1:639240148483:ios:585337a6fc40163c7d2036',
    messagingSenderId: '639240148483',
    projectId: 'ammarqiuckserve',
    storageBucket: 'ammarqiuckserve.appspot.com',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHHqMA25p-KmebPx9-NMHmuemHjjdSHZI',
    appId: '1:639240148483:web:5ff9e030ec7064ba7d2036',
    messagingSenderId: '639240148483',
    projectId: 'ammarqiuckserve',
    authDomain: 'ammarqiuckserve.firebaseapp.com',
    storageBucket: 'ammarqiuckserve.appspot.com',
  );
}
